{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "045c6462",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting mysql-connector-python\n",
      "  Using cached mysql_connector_python-8.0.28-py2.py3-none-any.whl (342 kB)\n",
      "Collecting protobuf>=3.0.0\n",
      "  Using cached protobuf-3.19.4-py2.py3-none-any.whl (162 kB)\n",
      "Installing collected packages: protobuf, mysql-connector-python\n",
      "Successfully installed mysql-connector-python-8.0.28 protobuf-3.19.4\n"
     ]
    }
   ],
   "source": [
    "!pip install mysql-connector-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "id": "64c8b035",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "###1번째 처리: 성공\n",
      "###2번째 처리: 성공\n",
      "###3번째 처리: 성공\n",
      "###4번째 처리: 성공\n",
      "###5번째 처리: 성공\n",
      "###6번째 처리: 성공\n",
      "###7번째 처리: 성공\n",
      "###8번째 처리: 성공\n",
      "###9번째 처리: 성공\n",
      "###10번째 처리: 성공\n",
      "###11번째 처리: 성공\n",
      "###12번째 처리: 성공\n",
      "###13번째 처리: 성공\n",
      "###14번째 처리: 성공\n",
      "###15번째 처리: 성공\n",
      "###16번째 처리: 성공\n",
      "###17번째 처리: 성공\n",
      "###18번째 처리: 성공\n",
      "###19번째 처리: 성공\n",
      "###20번째 처리: 성공\n",
      "###21번째 처리: 성공\n",
      "###22번째 처리: 성공\n",
      "###23번째 처리: 성공\n",
      "###24번째 처리: 성공\n",
      "###25번째 처리: 성공\n",
      "###26번째 처리: 성공\n",
      "###27번째 처리: 성공\n",
      "###28번째 처리: 성공\n",
      "###29번째 처리: 성공\n",
      "###30번째 처리: 성공\n",
      "###31번째 처리: 성공\n",
      "###32번째 처리: 성공\n",
      "###33번째 처리: 성공\n",
      "###34번째 처리: 성공\n",
      "###35번째 처리: 성공\n",
      "###36번째 처리: 성공\n",
      "###37번째 처리: 성공\n",
      "###38번째 처리: 성공\n",
      "###39번째 처리: 성공\n",
      "###40번째 처리: 성공\n",
      "###41번째 처리: 성공\n",
      "###42번째 처리: 성공\n",
      "###43번째 처리: 성공\n",
      "###44번째 처리: 성공\n",
      "###45번째 처리: 성공\n",
      "###46번째 처리: 성공\n",
      "###47번째 처리: 성공\n",
      "###48번째 처리: 성공\n",
      "###49번째 처리: 성공\n",
      "###50번째 처리: 성공\n",
      "###51번째 처리: 성공\n",
      "###52번째 처리: 성공\n",
      "###53번째 처리: 성공\n",
      "###54번째 처리: 성공\n",
      "###55번째 처리: 성공\n",
      "###56번째 처리: 성공\n",
      "###57번째 처리: 성공\n",
      "###58번째 처리: 성공\n",
      "###59번째 처리: 성공\n",
      "###60번째 처리: 성공\n",
      "###61번째 처리: 성공\n",
      "###62번째 처리: 성공\n",
      "###63번째 처리: 성공\n",
      "###64번째 처리: 성공\n",
      "###65번째 처리: 성공\n",
      "###66번째 처리: 성공\n",
      "###67번째 처리: 성공\n",
      "###68번째 처리: 성공\n",
      "###69번째 처리: 성공\n",
      "###70번째 처리: 성공\n",
      "###71번째 처리: 성공\n",
      "###72번째 처리: 성공\n",
      "###73번째 처리: 성공\n",
      "###74번째 처리: 성공\n",
      "###75번째 처리: 성공\n",
      "###76번째 처리: 성공\n",
      "###77번째 처리: 성공\n",
      "###78번째 처리: 성공\n",
      "###79번째 처리: 성공\n",
      "###80번째 처리: 성공\n",
      "###81번째 처리: 성공\n",
      "###82번째 처리: 성공\n",
      "###83번째 처리: 성공\n",
      "###84번째 처리: 성공\n",
      "###85번째 처리: 성공\n",
      "###86번째 처리: 성공\n",
      "###87번째 처리: 성공\n",
      "###88번째 처리: 성공\n",
      "###89번째 처리: 성공\n",
      "###90번째 처리: 성공\n",
      "###91번째 처리: 성공\n",
      "###92번째 처리: 성공\n",
      "###93번째 처리: 성공\n",
      "###94번째 처리: 성공\n",
      "###95번째 처리: 성공\n",
      "###96번째 처리: 성공\n",
      "###97번째 처리: 성공\n",
      "###98번째 처리: 성공\n",
      "###99번째 처리: 성공\n",
      "###100번째 처리: 성공\n",
      "###101번째 처리: 성공\n",
      "###102번째 처리: 성공\n",
      "###103번째 처리: 성공\n",
      "###104번째 처리: 성공\n",
      "###105번째 처리: 성공\n",
      "###106번째 처리: 성공\n",
      "###107번째 처리: 성공\n",
      "###108번째 처리: 성공\n",
      "###109번째 처리: 성공\n",
      "###110번째 처리: 성공\n",
      "###111번째 처리: 성공\n",
      "###112번째 처리: 성공\n",
      "###113번째 처리: 성공\n",
      "###114번째 처리: 성공\n",
      "###115번째 처리: 성공\n",
      "###116번째 처리: 성공\n",
      "###117번째 처리: 성공\n",
      "###118번째 처리: 성공\n",
      "###119번째 처리: 성공\n",
      "###120번째 처리: 성공\n",
      "###121번째 처리: 성공\n",
      "###122번째 처리: 성공\n",
      "###123번째 처리: 성공\n",
      "###124번째 처리: 성공\n",
      "###125번째 처리: 성공\n",
      "###126번째 처리: 성공\n",
      "###127번째 처리: 성공\n",
      "###128번째 처리: 성공\n",
      "###129번째 처리: 성공\n",
      "###130번째 처리: 성공\n",
      "###131번째 처리: 성공\n",
      "###132번째 처리: 성공\n",
      "###133번째 처리: 성공\n",
      "###134번째 처리: 성공\n",
      "###135번째 처리: 성공\n",
      "###136번째 처리: 성공\n",
      "###137번째 처리: 성공\n",
      "###138번째 처리: 성공\n",
      "###139번째 처리: 성공\n",
      "###140번째 처리: 성공\n",
      "###141번째 처리: 성공\n",
      "###142번째 처리: 성공\n",
      "###143번째 처리: 성공\n",
      "###144번째 처리: 성공\n",
      "###145번째 처리: 성공\n",
      "###146번째 처리: 성공\n",
      "###147번째 처리: 성공\n",
      "###148번째 처리: 성공\n",
      "###149번째 처리: 성공\n",
      "###150번째 처리: 성공\n",
      "###151번째 처리: 성공\n",
      "###152번째 처리: 성공\n",
      "###153번째 처리: 성공\n",
      "###154번째 처리: 성공\n",
      "###155번째 처리: 성공\n",
      "###156번째 처리: 성공\n",
      "###157번째 처리: 성공\n",
      "###158번째 처리: 성공\n",
      "###159번째 처리: 성공\n",
      "###160번째 처리: 성공\n",
      "###161번째 처리: 성공\n",
      "###162번째 처리: 성공\n",
      "###163번째 처리: 성공\n",
      "###164번째 처리: 성공\n",
      "###165번째 처리: 성공\n",
      "###166번째 처리: 성공\n",
      "###167번째 처리: 성공\n",
      "###168번째 처리: 성공\n",
      "###169번째 처리: 성공\n",
      "###170번째 처리: 성공\n",
      "###171번째 처리: 성공\n",
      "###172번째 처리: 성공\n",
      "###173번째 처리: 성공\n",
      "###174번째 처리: 성공\n",
      "###175번째 처리: 성공\n",
      "###176번째 처리: 성공\n",
      "###177번째 처리: 성공\n",
      "###178번째 처리: 성공\n",
      "###179번째 처리: 성공\n",
      "###180번째 처리: 성공\n",
      "###181번째 처리: 성공\n",
      "###182번째 처리: 성공\n",
      "###183번째 처리: 성공\n",
      "###184번째 처리: 성공\n",
      "###185번째 처리: 성공\n",
      "###186번째 처리: 성공\n",
      "###187번째 처리: 성공\n",
      "###188번째 처리: 성공\n",
      "###189번째 처리: 성공\n",
      "###190번째 처리: 성공\n",
      "###191번째 처리: 성공\n",
      "###192번째 처리: 성공\n",
      "###193번째 처리: 성공\n",
      "###194번째 처리: 성공\n",
      "###195번째 처리: 성공\n",
      "###196번째 처리: 성공\n",
      "###197번째 처리: 성공\n",
      "###198번째 처리: 성공\n",
      "###199번째 처리: 성공\n",
      "###200번째 처리: 성공\n",
      "###201번째 처리: 성공\n",
      "###202번째 처리: 성공\n",
      "###203번째 처리: 성공\n",
      "###204번째 처리: 성공\n",
      "###205번째 처리: 성공\n",
      "###206번째 처리: 성공\n",
      "###207번째 처리: 성공\n",
      "###208번째 처리: 성공\n",
      "###209번째 처리: 성공\n",
      "###210번째 처리: 성공\n",
      "###211번째 처리: 성공\n",
      "###212번째 처리: 성공\n",
      "###213번째 처리: 성공\n",
      "###214번째 처리: 성공\n",
      "###215번째 처리: 성공\n",
      "###216번째 처리: 성공\n",
      "###217번째 처리: 성공\n",
      "###218번째 처리: 성공\n",
      "###219번째 처리: 성공\n",
      "###220번째 처리: 성공\n",
      "###221번째 처리: 성공\n",
      "###222번째 처리: 성공\n",
      "###223번째 처리: 성공\n",
      "###224번째 처리: 성공\n",
      "###225번째 처리: 성공\n",
      "###226번째 처리: 성공\n",
      "###227번째 처리: 성공\n",
      "###228번째 처리: 성공\n",
      "###229번째 처리: 성공\n",
      "###230번째 처리: 성공\n",
      "###231번째 처리: 성공\n",
      "###232번째 처리: 성공\n",
      "###233번째 처리: 성공\n",
      "###234번째 처리: 성공\n",
      "###235번째 처리: 성공\n",
      "###236번째 처리: 성공\n",
      "###237번째 처리: 성공\n",
      "###238번째 처리: 성공\n",
      "###239번째 처리: 성공\n",
      "###240번째 처리: 성공\n",
      "###241번째 처리: 성공\n",
      "###242번째 처리: 성공\n",
      "###243번째 처리: 성공\n",
      "###244번째 처리: 성공\n",
      "###245번째 처리: 성공\n",
      "###246번째 처리: 성공\n",
      "###247번째 처리: 성공\n",
      "###248번째 처리: 성공\n",
      "###249번째 처리: 성공\n",
      "###250번째 처리: 성공\n",
      "###251번째 처리: 성공\n",
      "###252번째 처리: 성공\n",
      "###253번째 처리: 성공\n",
      "###254번째 처리: 성공\n",
      "###255번째 처리: 성공\n",
      "###256번째 처리: 성공\n",
      "###257번째 처리: 성공\n",
      "###258번째 처리: 성공\n",
      "###259번째 처리: 성공\n",
      "###260번째 처리: 성공\n",
      "###261번째 처리: 성공\n",
      "###262번째 처리: 성공\n",
      "###263번째 처리: 성공\n",
      "###264번째 처리: 성공\n",
      "###265번째 처리: 성공\n",
      "###266번째 처리: 성공\n",
      "###267번째 처리: 성공\n",
      "###268번째 처리: 성공\n",
      "###269번째 처리: 성공\n",
      "###270번째 처리: 성공\n",
      "###271번째 처리: 성공\n",
      "###272번째 처리: 성공\n",
      "###273번째 처리: 성공\n",
      "###274번째 처리: 성공\n",
      "###275번째 처리: 성공\n",
      "###276번째 처리: 성공\n",
      "###277번째 처리: 성공\n",
      "###278번째 처리: 성공\n",
      "###279번째 처리: 성공\n",
      "###280번째 처리: 성공\n",
      "###281번째 처리: 성공\n",
      "###282번째 처리: 성공\n",
      "###283번째 처리: 성공\n",
      "###284번째 처리: 성공\n",
      "###285번째 처리: 성공\n",
      "###286번째 처리: 성공\n",
      "###287번째 처리: 성공\n",
      "###288번째 처리: 성공\n",
      "###289번째 처리: 성공\n",
      "###290번째 처리: 성공\n",
      "###291번째 처리: 성공\n",
      "###292번째 처리: 성공\n",
      "###293번째 처리: 성공\n",
      "###294번째 처리: 성공\n",
      "###295번째 처리: 성공\n",
      "###296번째 처리: 성공\n",
      "###297번째 처리: 성공\n",
      "###298번째 처리: 성공\n",
      "###299번째 처리: 성공\n",
      "###300번째 처리: 성공\n",
      "###301번째 처리: 성공\n",
      "###302번째 처리: 성공\n",
      "###303번째 처리: 성공\n",
      "###304번째 처리: 성공\n",
      "###305번째 처리: 성공\n",
      "###306번째 처리: 성공\n",
      "###307번째 처리: 성공\n",
      "###308번째 처리: 성공\n",
      "###309번째 처리: 성공\n",
      "###310번째 처리: 성공\n",
      "###311번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 21.0 seconds\n",
      "###312번째 처리: 성공\n",
      "###313번째 처리: 성공\n",
      "###314번째 처리: 성공\n",
      "###315번째 처리: 성공\n",
      "###316번째 처리: 성공\n",
      "###317번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 20.0 seconds\n",
      "###318번째 처리: 성공\n",
      "###319번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 19.0 seconds\n",
      "###320번째 처리: 성공\n",
      "###321번째 처리: 성공\n",
      "###322번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 18.0 seconds\n",
      "###323번째 처리: 성공\n",
      "###324번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 17.0 seconds\n",
      "###325번째 처리: 성공\n",
      "###326번째 처리: 성공\n",
      "###327번째 처리: 성공\n",
      "###328번째 처리: 성공\n",
      "###329번째 처리: 성공\n",
      "###330번째 처리: 성공\n",
      "###331번째 처리: 성공\n",
      "###332번째 처리: 성공\n",
      "###333번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 15.0 seconds\n",
      "###334번째 처리: 성공\n",
      "###335번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 14.0 seconds\n",
      "###336번째 처리: 성공\n",
      "###337번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 13.0 seconds\n",
      "###338번째 처리: 성공\n",
      "###339번째 처리: 성공\n",
      "###340번째 처리: 성공\n",
      "###341번째 처리: 성공\n",
      "###342번째 처리: 성공\n",
      "###343번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 12.0 seconds\n",
      "###344번째 처리: 성공\n",
      "###345번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 11.0 seconds\n",
      "###346번째 처리: 성공\n",
      "###347번째 처리: 성공\n",
      "###348번째 처리: 성공\n",
      "###349번째 처리: 성공\n",
      "###350번째 처리: 성공\n",
      "###351번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 9.0 seconds\n",
      "###352번째 처리: 성공\n",
      "###353번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Timed out\n",
      "###354번째 처리: 성공\n",
      "###355번째 처리: 성공\n",
      "###356번째 처리: 성공\n",
      "###357번째 처리: 성공\n",
      "###358번째 처리: 성공\n",
      "###359번째 처리: 성공\n",
      "###360번째 처리: 성공\n",
      "###361번째 처리: 성공\n",
      "###362번째 처리: 성공\n",
      "###363번째 처리: 성공\n",
      "###364번째 처리: 성공\n",
      "###365번째 처리: 성공\n",
      "###366번째 처리: 성공\n",
      "###367번째 처리: 성공\n",
      "###368번째 처리: 성공\n",
      "###369번째 처리: 성공\n",
      "###370번째 처리: 성공\n",
      "###371번째 처리: 성공\n",
      "###372번째 처리: 성공\n",
      "###373번째 처리: 성공\n",
      "###374번째 처리: 성공\n",
      "###375번째 처리: 성공\n",
      "###376번째 처리: 성공\n",
      "###377번째 처리: 성공\n",
      "###378번째 처리: 성공\n",
      "###379번째 처리: 성공\n",
      "###380번째 처리: 성공\n",
      "###381번째 처리: 성공\n",
      "###382번째 처리: 성공\n",
      "###383번째 처리: 성공\n",
      "###384번째 처리: 성공\n",
      "###385번째 처리: 성공\n",
      "###386번째 처리: 성공\n",
      "###387번째 처리: 성공\n",
      "###388번째 처리: 성공\n",
      "###389번째 처리: 성공\n",
      "###390번째 처리: 성공\n",
      "###391번째 처리: 성공\n",
      "###392번째 처리: 성공\n",
      "###393번째 처리: 성공\n",
      "###394번째 처리: 성공\n",
      "###395번째 처리: 성공\n",
      "###396번째 처리: 성공\n",
      "###397번째 처리: 성공\n",
      "###398번째 처리: 성공\n",
      "###399번째 처리: 성공\n",
      "###400번째 처리: 성공\n",
      "###401번째 처리: 성공\n",
      "###402번째 처리: 성공\n",
      "###403번째 처리: 성공\n",
      "###404번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 36.0 seconds\n",
      "###405번째 처리: 성공\n",
      "###406번째 처리: 성공\n",
      "###407번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 35.0 seconds\n",
      "###408번째 처리: 성공\n",
      "###409번째 처리: 성공\n",
      "###410번째 처리: 성공\n",
      "###411번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 34.0 seconds\n",
      "###412번째 처리: 성공\n",
      "###413번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 33.0 seconds\n",
      "###414번째 처리: 성공\n",
      "###415번째 처리: 성공\n",
      "###416번째 처리: 성공\n",
      "###417번째 처리: 성공\n",
      "###418번째 처리: 성공\n",
      "###419번째 처리: 오류500메시지/이벤트처리:send_message_bot(): Flood control exceeded. Retry in 32.0 seconds\n",
      "###420번째 처리: 성공\n",
      "###421번째 처리: 성공\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f71f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b281f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089418b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fa00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e346a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28e20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f74c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b288b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b289a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889ff70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889ff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b282b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7df0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f74f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fd90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108429f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b281c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b283a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e349a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889ff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b289a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c0b5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941f10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089419a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089417f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889ff70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e340d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fa60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089413a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b281c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e343d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087dac40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28d60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f76a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087dac40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e342b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b29460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a46d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b282e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087dac10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a41c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d328b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089412b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a40a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c0b5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b282e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089416a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089411f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b282b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e349d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087daac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b285b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089413a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d321c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a41f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a09a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a40a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089419a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d328b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087daa00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a42e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d323a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089417c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b285b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a44f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4df0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d326d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fd90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4d60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108429f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087dab80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f72b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a40d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b283d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b284c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a45b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fa60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ce47f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4f10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f0a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b288b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d322e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e344c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d329d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a09a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105e53460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735f10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fa00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a45e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b289d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d328b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a42b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a40d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d327c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d323a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a47f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089413a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32df0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d323a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d324c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4df0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a46a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a02b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087354f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941d30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087daca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089414c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c7e400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f79a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087353a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b289a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10738c5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b289d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a02b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a48e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f70d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089413a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a09a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f77c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089413a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a48b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b284c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089413a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e341c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b281c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b288e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b289d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1093c8910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089416a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b284c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b282b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089938e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1093c8b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889ff70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e345b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089416d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a4b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fa00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a42b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084a48e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a44f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089416d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a41f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f71c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d32a60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e340a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fd30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7d30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e349d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d329d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d323a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b288b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108993430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d325b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da1f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108d326a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c0b5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089418b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a56d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1093c8490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a09a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fb80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1093c8f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108e34cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108735a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889fe50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108941f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1093c8c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10889f610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a5550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1085a02b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089a4ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1087da970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088a53d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108b28310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /monitor/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1089f7970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "###965번째 처리: 성공\n",
      "###966번째 처리: 성공\n",
      "###967번째 처리: 성공\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "###968번째 처리: 성공\n",
      "###969번째 처리: 성공\n",
      "###970번째 처리: 성공\n",
      "###971번째 처리: 성공\n",
      "###972번째 처리: 성공\n",
      "###973번째 처리: 성공\n",
      "###974번째 처리: 성공\n",
      "###975번째 처리: 성공\n",
      "###976번째 처리: 성공\n",
      "###977번째 처리: 성공\n",
      "###978번째 처리: 성공\n",
      "###979번째 처리: 성공\n",
      "###980번째 처리: 성공\n",
      "###981번째 처리: 성공\n",
      "###982번째 처리: 성공\n",
      "###983번째 처리: 성공\n",
      "###984번째 처리: 성공\n",
      "###985번째 처리: 성공\n",
      "###986번째 처리: 성공\n",
      "###987번째 처리: 성공\n",
      "###988번째 처리: 성공\n",
      "###989번째 처리: 성공\n",
      "###990번째 처리: 성공\n",
      "###991번째 처리: 성공\n"
     ]
    }
   ],
   "source": [
    "import mysql.connector\n",
    "import requests, json\n",
    "import time\n",
    "\n",
    "# 데이터베이스 컨넥션을 생성한다.\n",
    "mydb = mysql.connector.connect(\n",
    "    host=\"127.0.0.1\",\n",
    "    user=\"smartnqi\",\n",
    "    passwd=\"nwai1234!\",\n",
    "    database=\"smart\"\n",
    ")\n",
    "\n",
    "# 커서를 생성한다.\n",
    "cur = mydb.cursor()\n",
    "\n",
    "# 데이터를 조회할 쿼리문을 작성한다. \n",
    "sql = '''\n",
    "    select \n",
    "        'call' as dataType,\n",
    "        phone_no,\n",
    "        meastime,\n",
    "        networkId,\n",
    "        groupId,\n",
    "        currentTime,\n",
    "        timeline,\n",
    "        cellId,\n",
    "        currentCount,\n",
    "        ispId,\n",
    "        testNetworkType,\n",
    "        userInfo1,\n",
    "        userInfo2,\n",
    "        siDo,\n",
    "        guGun,\n",
    "        addressDetail,\n",
    "        udpJitter,\n",
    "        downloadBandwidth,\n",
    "        uploadBandwidth,\n",
    "        sinr,\n",
    "        isWifi,\n",
    "        latitude,\n",
    "        longitude,\n",
    "        bandType,\n",
    "        p_dl_earfcn,\n",
    "        p_pci,\n",
    "        p_rsrp,\n",
    "        p_SINR,\n",
    "        NR_EARFCN,\n",
    "        NR_PCI,\n",
    "        NR_RSRP,\n",
    "        NR_SINR\n",
    "        from tb_ndm_data_measure  \n",
    "        where \n",
    "            meastime between 20211101000000000 and 20211101235959999\n",
    "            and userInfo1 = '경상남도-사천시-남양동'\n",
    "            \n",
    "        order by savetime\n",
    "    '''\n",
    "\n",
    "# 쿼리문을 실행한다.\n",
    "cur.execute(sql)\n",
    "row_headers=[x[0] for x in cur.description]\n",
    "res = cur.fetchall()\n",
    "\n",
    "# 데이터를 가져와서 JSON 데이터를 생성한다.\n",
    "for idx, row in enumerate(res):\n",
    "    tmpData = dict(zip(row_headers,row))\n",
    "    jsonData = json.dumps(tmpData)\n",
    "    try:\n",
    "        r = requests.post(\"http://localhost:8000/monitor/json/\", data=jsonData)\n",
    "        # 전송실패 시 오류값을 출력한다.\n",
    "        if r.status_code == 200:\n",
    "            print(f\"###{idx+1}번째 처리: 성공\")\n",
    "        else:\n",
    "            print(f\"###{idx+1}번째 처리: 오류{r.status_code}{r.text}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(str(e))\n",
    "\n",
    "#     # 초당 3개씩 전달하도록 한다. \n",
    "#     # 너무 다량의 데이터를 연속해서 보내면 서버단에서 부하로 오류가 발생한다. \n",
    "#     if idx % 3 == 0:\n",
    "#         time.sleep(1)\n",
    "                  "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ebdee317",
   "metadata": {
    "collapsed": true
   },
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
